# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mensaje_main.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mensaje_main.proto',
  package='mensaje',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12mensaje_main.proto\x12\x07mensaje\",\n\x0bSomnolencia\x12\x0e\n\x06\x61vgEAR\x18\x01 \x01(\x02\x12\r\n\x05\x61lert\x18\x02 \x01(\x08\x62\x06proto3'
)




_SOMNOLENCIA = _descriptor.Descriptor(
  name='Somnolencia',
  full_name='mensaje.Somnolencia',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='avgEAR', full_name='mensaje.Somnolencia.avgEAR', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alert', full_name='mensaje.Somnolencia.alert', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['Somnolencia'] = _SOMNOLENCIA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Somnolencia = _reflection.GeneratedProtocolMessageType('Somnolencia', (_message.Message,), {
  'DESCRIPTOR' : _SOMNOLENCIA,
  '__module__' : 'mensaje_main_pb2'
  # @@protoc_insertion_point(class_scope:mensaje.Somnolencia)
  })
_sym_db.RegisterMessage(Somnolencia)


# @@protoc_insertion_point(module_scope)
